name: OHI CI-CD to Azure App

on:
  push:
    branches:
      - dev



jobs:
  build:
    name: DotNet Build
    runs-on: ubuntu-20.04
    steps:
    
      - uses: action/checkout@v3
      - name: Setup Dotnet Environment
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 3.1.103
          
      - name: Dotnet Publish
        run: dotnet publish -c Release -o .pub
