name: OHI CI-CD to Azure App

on:
  push:
    branches:
      - main



jobs:
  build:
    name: DotNet Build
    runs-on: ubuntu-20.04
    steps:
    # setup dotnet
      - uses: action/checkout@main
      - name: Setup Dotnet Environment
      - uses: actions/setup-dotnet@2.1.0
        with:
          dotnet-version: 3.1.103
      - name: Dotnet Publish
        run: dotnet publish -c Release -o .pub
